import type {
  AnyAgentTool,
  OpenClawPluginApi,
  OpenClawPluginToolContext
} from "openclaw/plugin-sdk/core";

import {
  artifactListParamsZod,
  campaignActionParamsZod,
  campaignRunParamsZod,
  campaignStatusParamsZod,
  contextSyncParamsZod,
  costParamsZod,
  forkParamsZod,
  logsParamsZod,
  projectCreateParamsZod,
  resumeParamsZod,
  sendParamsZod,
  siteStatusParamsZod,
  startParamsZod,
  statusParamsZod,
  stopParamsZod,
  toolArtifactsSchema,
  toolCampaignActionSchema,
  toolCampaignRunSchema,
  toolCampaignStatusSchema,
  toolContextSyncSchema,
  toolCostSchema,
  toolForkSchema,
  toolLogsSchema,
  toolProjectCreateSchema,
  toolResumeSchema,
  toolSendSchema,
  toolSiteStatusSchema,
  toolStartSchema,
  toolStatusSchema,
  toolStopSchema,
  toolWorkerRegisterSchema,
  workerManifestZod
} from "../shared/schema.js";
import { patchStoredSession, getPuppenclawManager, getPuppenclawOrchestrator } from "./service.js";

function flattenToolText(result: { content: Array<{ text: string }> }): string {
  return result.content.map((entry) => entry.text).join("\n").trim();
}

function annotateToolSessionSource(toolCtx: OpenClawPluginToolContext, name: string): Promise<void> {
  return patchStoredSession(name, (session) => {
    if (session == null) {
      return session;
    }
    return {
      ...session,
      source: {
        kind: "tool",
        ...(toolCtx.messageChannel != null ? { channel: toolCtx.messageChannel } : {}),
        ...(toolCtx.requesterSenderId != null
          ? { requesterSenderId: toolCtx.requesterSenderId }
          : {})
      }
    };
  }).then(() => undefined);
}

function createTools(toolCtx: OpenClawPluginToolContext): AnyAgentTool[] {
  return [
    {
      name: "puppenclaw_project_create",
      label: "Create Puppenclaw project",
      description: "Register a project root and metadata for orchestrated coding, research, and experiment runs.",
      parameters: toolProjectCreateSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.createProject(projectCreateParamsZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_worker_register",
      label: "Register Puppenclaw worker",
      description: "Register or update a worker capability manifest for orchestrated campaigns.",
      parameters: toolWorkerRegisterSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.registerWorker(workerManifestZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_context_sync",
      label: "Sync project context",
      description: "Capture project context files and memory into a reusable orchestration bundle.",
      parameters: toolContextSyncSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.syncContext(contextSyncParamsZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_campaign_start",
      label: "Start Puppenclaw campaign",
      description: "Run a high-level project campaign such as baseline, literature review, ablations, or a self-improvement loop.",
      parameters: toolCampaignRunSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.runCampaign(campaignRunParamsZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_campaign_status",
      label: "Puppenclaw campaign status",
      description: "Inspect orchestration projects, campaigns, workers, and run state.",
      parameters: toolCampaignStatusSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.status(campaignStatusParamsZod.parse(rawParams ?? {}));
      }
    },
    {
      name: "puppenclaw_artifacts",
      label: "Puppenclaw artifacts",
      description: "List project or campaign artifacts generated by orchestrated runs.",
      parameters: toolArtifactsSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.listArtifacts(artifactListParamsZod.parse(rawParams ?? {}));
      }
    },
    {
      name: "puppenclaw_campaign_approve",
      label: "Approve Puppenclaw campaign step",
      description: "Approve a paused orchestration campaign and resume execution.",
      parameters: toolCampaignActionSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.approve(campaignActionParamsZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_campaign_cancel",
      label: "Cancel Puppenclaw campaign",
      description: "Cancel an active or paused orchestration campaign.",
      parameters: toolCampaignActionSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.cancel(campaignActionParamsZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_site_status",
      label: "Puppenclaw site status",
      description: "Inspect site-level runtime health, capacity, workers, and remote-control exposure state.",
      parameters: toolSiteStatusSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.siteStatus(siteStatusParamsZod.parse(rawParams ?? {}));
      }
    },
    {
      name: "puppenclaw_logs",
      label: "Puppenclaw logs",
      description: "Fetch bounded session, run, or campaign logs for remote inspection and polling.",
      parameters: toolLogsSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const orchestrator = await getPuppenclawOrchestrator();
        return orchestrator.logs(logsParamsZod.parse(rawParams));
      }
    },
    {
      name: "puppenclaw_start",
      label: "Start Puppenclaw session",
      description: "Start or reuse a managed ACP session for Claude Code or Codex.",
      parameters: toolStartSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const params = startParamsZod.parse(rawParams);
        const result = await manager.start(params);
        await annotateToolSessionSource(toolCtx, params.name);
        return {
          content: result.content,
          details: result.details
        };
      }
    },
    {
      name: "puppenclaw_send",
      label: "Send Puppenclaw message",
      description: "Send another message into an existing Puppenclaw-managed session.",
      parameters: toolSendSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const params = sendParamsZod.parse(rawParams);
        const result = await manager.send(params);
        return {
          content: result.content,
          details: result.details
        };
      }
    },
    {
      name: "puppenclaw_status",
      label: "Puppenclaw status",
      description: "Inspect one managed session or list all managed sessions.",
      parameters: toolStatusSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const result = await manager.status(statusParamsZod.parse(rawParams ?? {}));
        return {
          content: result.content,
          details: result.details
        };
      }
    },
    {
      name: "puppenclaw_stop",
      label: "Stop Puppenclaw session",
      description: "Stop an active Puppenclaw-managed session.",
      parameters: toolStopSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const result = await manager.stop(stopParamsZod.parse(rawParams));
        return {
          content: result.content,
          details: result.details
        };
      }
    },
    {
      name: "puppenclaw_resume",
      label: "Resume Puppenclaw session",
      description: "Mark a stopped session as resumable again.",
      parameters: toolResumeSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const result = await manager.resume(resumeParamsZod.parse(rawParams));
        return {
          content: result.content,
          details: result.details
        };
      }
    },
    {
      name: "puppenclaw_fork",
      label: "Fork Puppenclaw session",
      description: "Create a new session from the transcript of an existing session.",
      parameters: toolForkSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const result = await manager.fork(forkParamsZod.parse(rawParams));
        return {
          content: result.content,
          details: result.details
        };
      }
    },
    {
      name: "puppenclaw_cost",
      label: "Puppenclaw usage",
      description: "Return recorded usage counters for a managed session.",
      parameters: toolCostSchema,
      execute: async (_toolCallId: string, rawParams: unknown) => {
        const manager = await getPuppenclawManager();
        const result = await manager.cost(costParamsZod.parse(rawParams));
        return {
          content: result.content,
          details: result.details
        };
      }
    }
  ].map((tool) => ({
    ...tool,
    displaySummary: tool.name
  }));
}

export function registerPuppenclawTools(api: OpenClawPluginApi): void {
  api.registerTool((toolCtx: OpenClawPluginToolContext) => createTools(toolCtx));
}

export function summarizeToolResultText(result: { content: Array<{ text: string }> }): string {
  return flattenToolText(result);
}
